#ifndef HDS_FEATURES_H
#define HDS_FEATURES_H

#if defined(HDS_CUSTOM_BUILD)
#include "generated_features.h"
#endif

#ifndef HDS_FEATURE_WIFI
#define HDS_FEATURE_WIFI 1
#endif
#ifndef HDS_FEATURE_MDNS
#define HDS_FEATURE_MDNS 1
#endif
#ifndef HDS_FEATURE_WEBSERVER
#define HDS_FEATURE_WEBSERVER 1
#endif
#ifndef HDS_FEATURE_WEBSOCKET
#define HDS_FEATURE_WEBSOCKET 1
#endif
#ifndef HDS_FEATURE_LITTLEFS
#define HDS_FEATURE_LITTLEFS 1
#endif
#ifndef HDS_FEATURE_ELEGANT_OTA
#define HDS_FEATURE_ELEGANT_OTA 1
#endif
#ifndef HDS_FEATURE_PULL_OTA
#define HDS_FEATURE_PULL_OTA 1
#endif
#ifndef HDS_FEATURE_GRINDER
#ifdef HDS_ENABLE_GRINDER
#define HDS_FEATURE_GRINDER HDS_ENABLE_GRINDER
#else
#define HDS_FEATURE_GRINDER 0
#endif
#endif

#if (HDS_FEATURE_WIFI != 0 && HDS_FEATURE_WIFI != 1) || \
    (HDS_FEATURE_MDNS != 0 && HDS_FEATURE_MDNS != 1) || \
    (HDS_FEATURE_WEBSERVER != 0 && HDS_FEATURE_WEBSERVER != 1) || \
    (HDS_FEATURE_WEBSOCKET != 0 && HDS_FEATURE_WEBSOCKET != 1) || \
    (HDS_FEATURE_LITTLEFS != 0 && HDS_FEATURE_LITTLEFS != 1) || \
    (HDS_FEATURE_ELEGANT_OTA != 0 && HDS_FEATURE_ELEGANT_OTA != 1) || \
    (HDS_FEATURE_PULL_OTA != 0 && HDS_FEATURE_PULL_OTA != 1) || \
    (HDS_FEATURE_GRINDER != 0 && HDS_FEATURE_GRINDER != 1)
#error "HDS feature macros must be numeric 0 or 1"
#endif

#if HDS_FEATURE_WEBSERVER && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_WEBSERVER requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_MDNS && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_MDNS requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_WEBSOCKET && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_WEBSOCKET requires WIFI and WEBSERVER"
#endif
#if HDS_FEATURE_ELEGANT_OTA && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_ELEGANT_OTA requires WIFI and WEBSERVER"
#endif
#if HDS_FEATURE_PULL_OTA && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_PULL_OTA requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_GRINDER && (!HDS_FEATURE_WIFI || !HDS_FEATURE_MDNS)
#error "HDS_FEATURE_GRINDER requires WIFI and MDNS"
#endif

#undef HDS_ENABLE_GRINDER
#define HDS_ENABLE_GRINDER HDS_FEATURE_GRINDER

#endif
