#ifndef HDS_FEATURES_H
#define HDS_FEATURES_H

#ifndef HDS_CUSTOM_BUILD
#define HDS_CUSTOM_BUILD 0
#endif

#if HDS_CUSTOM_BUILD
#include "generated_features.h"
#else
#define HDS_FEATURE_WIFI 1
#define HDS_FEATURE_MDNS 1
#define HDS_FEATURE_WEBSERVER 1
#define HDS_FEATURE_WEBSOCKET 1
#define HDS_FEATURE_LITTLEFS 1
#define HDS_FEATURE_ELEGANT_OTA 1
#define HDS_FEATURE_PULL_OTA 1
#ifdef HDS_ENABLE_GRINDER
#define HDS_FEATURE_GRINDER HDS_ENABLE_GRINDER
#else
#define HDS_FEATURE_GRINDER 0
#endif
#endif

#if (HDS_FEATURE_WIFI != 0 && HDS_FEATURE_WIFI != 1) || \
    (HDS_FEATURE_MDNS != 0 && HDS_FEATURE_MDNS != 1) || \
    (HDS_FEATURE_WEBSERVER != 0 && HDS_FEATURE_WEBSERVER != 1) || \
    (HDS_FEATURE_WEBSOCKET != 0 && HDS_FEATURE_WEBSOCKET != 1) || \
    (HDS_FEATURE_LITTLEFS != 0 && HDS_FEATURE_LITTLEFS != 1) || \
    (HDS_FEATURE_ELEGANT_OTA != 0 && HDS_FEATURE_ELEGANT_OTA != 1) || \
    (HDS_FEATURE_PULL_OTA != 0 && HDS_FEATURE_PULL_OTA != 1) || \
    (HDS_FEATURE_GRINDER != 0 && HDS_FEATURE_GRINDER != 1)
#error "HDS feature macros must be 0 or 1"
#endif

#if HDS_FEATURE_MDNS && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_MDNS requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_WEBSERVER && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_WEBSERVER requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_WEBSOCKET && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_WEBSOCKET requires HDS_FEATURE_WIFI and HDS_FEATURE_WEBSERVER"
#endif
#if HDS_FEATURE_ELEGANT_OTA && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_ELEGANT_OTA requires HDS_FEATURE_WIFI and HDS_FEATURE_WEBSERVER"
#endif
#if HDS_FEATURE_PULL_OTA && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_PULL_OTA requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_GRINDER && (!HDS_FEATURE_WIFI || !HDS_FEATURE_MDNS)
#error "HDS_FEATURE_GRINDER requires HDS_FEATURE_WIFI and HDS_FEATURE_MDNS"
#endif

#ifdef HDS_ENABLE_GRINDER
#if HDS_ENABLE_GRINDER != HDS_FEATURE_GRINDER
#error "HDS_ENABLE_GRINDER conflicts with HDS_FEATURE_GRINDER"
#endif
#else
#define HDS_ENABLE_GRINDER HDS_FEATURE_GRINDER
#endif

#endif
