#ifndef HDS_FEATURES_H
#define HDS_FEATURES_H

#ifndef HDS_ENABLE_GRINDER
#define HDS_ENABLE_GRINDER 0
#endif

#ifndef HDS_FEATURE_WIFI
#define HDS_FEATURE_WIFI 1
#endif
#ifndef HDS_FEATURE_MDNS
#define HDS_FEATURE_MDNS 1
#endif
#ifndef HDS_FEATURE_WEBSERVER
#define HDS_FEATURE_WEBSERVER 1
#endif
#ifndef HDS_FEATURE_WEBSOCKET
#define HDS_FEATURE_WEBSOCKET 1
#endif
#ifndef HDS_FEATURE_LITTLEFS
#define HDS_FEATURE_LITTLEFS 1
#endif
#ifndef HDS_FEATURE_ELEGANT_OTA
#define HDS_FEATURE_ELEGANT_OTA 1
#endif
#ifndef HDS_FEATURE_PULL_OTA
#define HDS_FEATURE_PULL_OTA 1
#endif
#ifndef HDS_FEATURE_GRINDER
#define HDS_FEATURE_GRINDER HDS_ENABLE_GRINDER
#endif

#if (HDS_FEATURE_WIFI != 0) && (HDS_FEATURE_WIFI != 1)
#error "HDS_FEATURE_WIFI must be 0 or 1"
#endif
#if (HDS_FEATURE_MDNS != 0) && (HDS_FEATURE_MDNS != 1)
#error "HDS_FEATURE_MDNS must be 0 or 1"
#endif
#if (HDS_FEATURE_WEBSERVER != 0) && (HDS_FEATURE_WEBSERVER != 1)
#error "HDS_FEATURE_WEBSERVER must be 0 or 1"
#endif
#if (HDS_FEATURE_WEBSOCKET != 0) && (HDS_FEATURE_WEBSOCKET != 1)
#error "HDS_FEATURE_WEBSOCKET must be 0 or 1"
#endif
#if (HDS_FEATURE_LITTLEFS != 0) && (HDS_FEATURE_LITTLEFS != 1)
#error "HDS_FEATURE_LITTLEFS must be 0 or 1"
#endif
#if (HDS_FEATURE_ELEGANT_OTA != 0) && (HDS_FEATURE_ELEGANT_OTA != 1)
#error "HDS_FEATURE_ELEGANT_OTA must be 0 or 1"
#endif
#if (HDS_FEATURE_PULL_OTA != 0) && (HDS_FEATURE_PULL_OTA != 1)
#error "HDS_FEATURE_PULL_OTA must be 0 or 1"
#endif
#if (HDS_FEATURE_GRINDER != 0) && (HDS_FEATURE_GRINDER != 1)
#error "HDS_FEATURE_GRINDER must be 0 or 1"
#endif

#if HDS_FEATURE_WEBSERVER && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_WEBSERVER requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_MDNS && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_MDNS requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_WEBSOCKET && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_WEBSOCKET requires HDS_FEATURE_WIFI and HDS_FEATURE_WEBSERVER"
#endif
#if HDS_FEATURE_ELEGANT_OTA && (!HDS_FEATURE_WIFI || !HDS_FEATURE_WEBSERVER)
#error "HDS_FEATURE_ELEGANT_OTA requires HDS_FEATURE_WIFI and HDS_FEATURE_WEBSERVER"
#endif
#if HDS_FEATURE_PULL_OTA && !HDS_FEATURE_WIFI
#error "HDS_FEATURE_PULL_OTA requires HDS_FEATURE_WIFI"
#endif
#if HDS_FEATURE_GRINDER && (!HDS_FEATURE_WIFI || !HDS_FEATURE_MDNS)
#error "HDS_FEATURE_GRINDER requires HDS_FEATURE_WIFI and HDS_FEATURE_MDNS"
#endif
#if HDS_FEATURE_GRINDER != HDS_ENABLE_GRINDER
#error "HDS_FEATURE_GRINDER and HDS_ENABLE_GRINDER must match"
#endif
#if defined(ESPNOW) && !HDS_FEATURE_WIFI
#error "ESPNOW requires HDS_FEATURE_WIFI"
#endif

#endif
