
name: Build firmware

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - esp32s3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-node@v4.1.0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: |
          pio run -e ${{ matrix.board }} 
          pio run -e ${{ matrix.board }} -t buildfs

      - name: Save firmware file
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}
          path: |
            .pio.nosync/build/${{ matrix.board }}/firmware.bin
            .pio.nosync/build/${{ matrix.board }}/spiffs.bin
